/* Seed Nacional 2 — marcas/modelos do mercado PT, utilizadores demo e carros exemplo */
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const BRANDS: Record<string, string[]> = {
  Abarth: ["500", "595", "695"],
  "Alfa Romeo": ["Giulia", "Giulietta", "MiTo", "Stelvio", "Tonale"],
  Audi: [
    "A1",
    "A3",
    "A3 Sportback",
    "A4",
    "A4 Avant",
    "A5",
    "A6",
    "A6 Avant",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q7",
    "Q8",
    "e-tron",
    "e-tron GT",
    "TT",
  ],
  BMW: [
    "Série 1",
    "Série 2",
    "Série 2 Active Tourer",
    "Série 3",
    "Série 3 Touring",
    "Série 4",
    "Série 5",
    "Série 5 Touring",
    "Série 7",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "i3",
    "i4",
    "iX",
    "iX1",
    "iX3",
    "Z4",
  ],
  BYD: ["Atto 3", "Dolphin", "Han", "Seal", "Tang"],
  Citroën: [
    "Berlingo",
    "C1",
    "C3",
    "C3 Aircross",
    "C4",
    "C4 X",
    "C5 Aircross",
    "C5 X",
    "ë-C4",
    "Jumpy",
    "Xsara Picasso",
  ],
  Cupra: ["Ateca", "Born", "Formentor", "Leon", "Tavascan"],
  Dacia: [
    "Dokker",
    "Duster",
    "Jogger",
    "Lodgy",
    "Logan",
    "Sandero",
    "Sandero Stepway",
    "Spring",
  ],
  DS: ["DS3", "DS3 Crossback", "DS4", "DS7", "DS7 Crossback", "DS9"],
  Fiat: ["500", "500e", "500X", "Doblo", "Panda", "Punto", "Tipo"],
  Ford: [
    "EcoSport",
    "Fiesta",
    "Focus",
    "Galaxy",
    "Ka",
    "Kuga",
    "Mondeo",
    "Mustang",
    "Mustang Mach-E",
    "Puma",
    "Ranger",
    "S-Max",
    "Transit",
  ],
  Honda: ["Civic", "CR-V", "e:Ny1", "HR-V", "Jazz"],
  Hyundai: [
    "Bayon",
    "i10",
    "i20",
    "i30",
    "IONIQ",
    "IONIQ 5",
    "IONIQ 6",
    "Kauai",
    "Kona",
    "Santa Fe",
    "Tucson",
  ],
  Jaguar: ["E-Pace", "F-Pace", "I-Pace", "XE", "XF"],
  Jeep: ["Avenger", "Compass", "Renegade", "Wrangler"],
  Kia: [
    "Ceed",
    "EV6",
    "EV9",
    "Niro",
    "Picanto",
    "Rio",
    "Sorento",
    "Sportage",
    "Stonic",
    "XCeed",
  ],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
  ],
  Lexus: ["CT", "ES", "NX", "RX", "UX"],
  Mazda: ["2", "3", "6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-30", "MX-5"],
  "Mercedes-Benz": [
    "Classe A",
    "Classe B",
    "Classe C",
    "Classe E",
    "Classe S",
    "CLA",
    "CLS",
    "EQA",
    "EQB",
    "EQC",
    "EQE",
    "EQS",
    "GLA",
    "GLB",
    "GLC",
    "GLC Coupé",
    "GLE",
    "Vito",
  ],
  MG: ["EHS", "MG4", "MG5", "ZS", "ZS EV"],
  Mini: ["Cabrio", "Clubman", "Cooper", "Countryman", "Electric"],
  Mitsubishi: ["ASX", "Eclipse Cross", "Outlander", "Space Star"],
  Nissan: ["Ariya", "Juke", "Leaf", "Micra", "Navara", "Qashqai", "X-Trail"],
  Opel: [
    "Astra",
    "Combo",
    "Corsa",
    "Corsa-e",
    "Crossland",
    "Grandland",
    "Insignia",
    "Mokka",
    "Mokka-e",
    "Zafira",
  ],
  Peugeot: [
    "108",
    "2008",
    "208",
    "3008",
    "308",
    "308 SW",
    "408",
    "5008",
    "508",
    "e-2008",
    "e-208",
    "Partner",
    "Rifter",
  ],
  Polestar: ["Polestar 2", "Polestar 3"],
  Porsche: ["718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  Renault: [
    "Arkana",
    "Austral",
    "Captur",
    "Clio",
    "Espace",
    "Kadjar",
    "Kangoo",
    "Mégane",
    "Mégane E-Tech",
    "Scénic",
    "Twingo",
    "Zoe",
  ],
  Seat: ["Alhambra", "Arona", "Ateca", "Ibiza", "Leon", "Tarraco"],
  Skoda: [
    "Enyaq",
    "Fabia",
    "Kamiq",
    "Karoq",
    "Kodiaq",
    "Octavia",
    "Scala",
    "Superb",
  ],
  Smart: ["#1", "#3", "ForFour", "ForTwo"],
  Subaru: ["Forester", "Outback", "XV"],
  Suzuki: ["Ignis", "Jimny", "S-Cross", "Swift", "Vitara"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  Toyota: [
    "Aygo",
    "Aygo X",
    "bZ4X",
    "C-HR",
    "Corolla",
    "Corolla Touring Sports",
    "Hilux",
    "Land Cruiser",
    "Prius",
    "RAV4",
    "Supra",
    "Yaris",
    "Yaris Cross",
  ],
  Volkswagen: [
    "Arteon",
    "Caddy",
    "Golf",
    "Golf Variant",
    "ID.3",
    "ID.4",
    "ID.5",
    "ID.7",
    "Passat",
    "Polo",
    "T-Cross",
    "T-Roc",
    "Taigo",
    "Tiguan",
    "Touareg",
    "Touran",
    "Up!",
  ],
  Volvo: [
    "C40",
    "EX30",
    "EX90",
    "S60",
    "S90",
    "V60",
    "V90",
    "XC40",
    "XC60",
    "XC90",
  ],
};

async function main() {
  console.log("🌱 Seeding Nacional 2…");

  console.log("→ marcas e modelos…");
  const modelId: Record<string, { brandId: number; modelId: number }> = {};
  for (const [name, models] of Object.entries(BRANDS)) {
    const brand = await prisma.brand.upsert({
      where: { name },
      update: {},
      create: { name },
    });
    for (const m of models) {
      const model = await prisma.model.upsert({
        where: { brandId_name: { brandId: brand.id, name: m } },
        update: {},
        create: { brandId: brand.id, name: m },
      });
      modelId[`${name}|${m}`] = { brandId: brand.id, modelId: model.id };
    }
  }

  console.log("→ utilizadores…");
  const mk = async (
    name: string,
    email: string,
    pass: string,
    role: string,
    district: string
  ) =>
    prisma.user.upsert({
      where: { email },
      update: { role },
      create: {
        name,
        email,
        passwordHash: await bcrypt.hash(pass, 12),
        role,
        district,
      },
    });
  await mk(
    "Equipa Nacional 2",
    "admin@nacional2.pt",
    "admin123",
    "ADMIN",
    "Viseu"
  );
  const maria = await mk(
    "Maria Fonseca",
    "maria@email.pt",
    "demo1234",
    "USER",
    "Viseu"
  );
  const joao = await mk(
    "João Ribeiro",
    "joao@email.pt",
    "demo1234",
    "USER",
    "Lisboa"
  );

  if ((await prisma.car.count()) === 0) {
    console.log("→ carros exemplo…");
    const cars = [
      {
        o: maria,
        b: "Toyota",
        m: "Corolla",
        v: "1.8 Hybrid Comfort",
        year: 2022,
        km: 38500,
        fuel: "Híbrido",
        gear: "Automática",
        cv: 122,
        range: null as number | null,
        d: "Viseu",
        sale: true,
        price: 22900 as number | null,
        nego: true,
        st: "APPROVED",
        color: "#CE994B",
      },
      {
        o: maria,
        b: "Renault",
        m: "Clio",
        v: "1.0 TCe Techno",
        year: 2023,
        km: 21000,
        fuel: "Gasolina",
        gear: "Manual",
        cv: 90,
        range: null,
        d: "Viseu",
        sale: true,
        price: 16700,
        nego: true,
        st: "APPROVED",
        color: "#B4552D",
      },
      {
        o: maria,
        b: "Peugeot",
        m: "208",
        v: "1.2 PureTech Style",
        year: 2021,
        km: 52300,
        fuel: "Gasolina",
        gear: "Manual",
        cv: 100,
        range: null,
        d: "Viseu",
        sale: false,
        price: null,
        nego: true,
        st: "GARAGE",
        color: "#8B8165",
      },
      {
        o: joao,
        b: "Tesla",
        m: "Model 3",
        v: "Long Range AWD",
        year: 2022,
        km: 41200,
        fuel: "Elétrico",
        gear: "Automática",
        cv: 498,
        range: 560,
        d: "Lisboa",
        sale: true,
        price: 32900,
        nego: true,
        st: "APPROVED",
        color: "#7E93A0",
      },
      {
        o: joao,
        b: "Renault",
        m: "Mégane E-Tech",
        v: "EV60 Techno",
        year: 2023,
        km: 26400,
        fuel: "Elétrico",
        gear: "Automática",
        cv: 218,
        range: 450,
        d: "Lisboa",
        sale: true,
        price: 28900,
        nego: true,
        st: "APPROVED",
        color: "#556217",
      },
      {
        o: joao,
        b: "Volkswagen",
        m: "Golf",
        v: "2.0 TDI Life",
        year: 2020,
        km: 89000,
        fuel: "Diesel",
        gear: "Manual",
        cv: 115,
        range: null,
        d: "Lisboa",
        sale: true,
        price: 19400,
        nego: true,
        st: "APPROVED",
        color: "#414D11",
      },
      {
        o: joao,
        b: "Dacia",
        m: "Spring",
        v: "Electric 45 Comfort",
        year: 2022,
        km: 19800,
        fuel: "Elétrico",
        gear: "Automática",
        cv: 44,
        range: 230,
        d: "Lisboa",
        sale: true,
        price: 13900,
        nego: true,
        st: "APPROVED",
        color: "#D8B06A",
      },
      {
        o: maria,
        b: "BMW",
        m: "Série 1",
        v: "116d Advantage",
        year: 2019,
        km: 112000,
        fuel: "Diesel",
        gear: "Automática",
        cv: 116,
        range: null,
        d: "Viseu",
        sale: true,
        price: 18900,
        nego: true,
        st: "PENDING",
        color: "#2A2721",
      },
      {
        o: joao,
        b: "Peugeot",
        m: "e-208",
        v: "GT 50 kWh",
        year: 2021,
        km: 33500,
        fuel: "Elétrico",
        gear: "Automática",
        cv: 136,
        range: 340,
        d: "Lisboa",
        sale: true,
        price: 21500,
        nego: false,
        st: "APPROVED",
        color: "#A34A28",
      },
      {
        o: maria,
        b: "Volkswagen",
        m: "T-Roc",
        v: "1.5 TSI Style",
        year: 2022,
        km: 47300,
        fuel: "Gasolina",
        gear: "Manual",
        cv: 150,
        range: null,
        d: "Viseu",
        sale: true,
        price: 23400,
        nego: true,
        st: "APPROVED",
        color: "#624E1C",
      },
    ];
    const created = [];
    for (const c of cars) {
      const ids = modelId[`${c.b}|${c.m}`];
      created.push(
        await prisma.car.create({
          data: {
            ownerId: c.o.id,
            brandId: ids.brandId,
            modelId: ids.modelId,
            version: c.v,
            year: c.year,
            km: c.km,
            fuel: c.fuel,
            gearbox: c.gear,
            power: c.cv,
            evRange: c.range,
            district: c.d,
            forSale: c.sale,
            price: c.price,
            negotiable: c.nego,
            status: c.st,
            color: c.color,
            description: `${c.b} ${c.m} ${c.v}. Muito bem estimado, revisões em dia, pronto a seguir viagem.`,
          },
        })
      );
    }

    console.log("→ lembretes e ofertas…");
    const inDays = (d: number) => new Date(Date.now() + d * 86400000);
    await prisma.reminder.createMany({
      data: [
        {
          carId: created[2].id,
          type: "IPO",
          title: "Inspeção periódica obrigatória",
          dueDate: inDays(21),
        },
        {
          carId: created[2].id,
          type: "Manutenção",
          title: "Revisão dos 60 000 km",
          dueDate: inDays(60),
        },
        {
          carId: created[0].id,
          type: "Seguro",
          title: "Renovação do seguro",
          dueDate: inDays(12),
        },
        {
          carId: created[3].id,
          type: "Pneus",
          title: "Trocar pneus dianteiros",
          dueDate: inDays(45),
        },
      ],
    });
    await prisma.offer.createMany({
      data: [
        {
          carId: created[0].id,
          buyerId: joao.id,
          amount: 21500,
          message: "Bom dia! Aceita 21.500€ com transferência imediata?",
        },
        {
          carId: created[3].id,
          buyerId: maria.id,
          amount: 31000,
          message: "Interessada, posso ver o carro este fim de semana.",
        },
      ],
    });
  }

  const b = await prisma.brand.count();
  const m = await prisma.model.count();
  console.log(`✅ Seed completo: ${b} marcas, ${m} modelos.`);
  console.log("\n📧 Contas demo:");
  console.log("   admin@nacional2.pt / admin123  (ADMIN — /admin)");
  console.log("   maria@email.pt / demo1234");
  console.log("   joao@email.pt / demo1234");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
